### ISSUE TITLE
Ink looks like water

### ISSUE THREAD

**Issue by snowei19** [ZenkakuHiragana/splatoonsweps#1]
So the ink looks like water, except when it's on dynamic terrain or whatever it's called.

OS : Windows 10 64bit
CPU : AMD Athlon II X4 640 3.00 GHz
RAM : 6 GB
GPU : AMD Radeon HD 5700 Series
(yeah my pc is trash)

I don't think my subscribed addons are conflicting with the sweps, and I didn't really have any cache files, because I reinstalled gmod a while ago.
![20200330172123_1](https://user-images.githubusercontent.com/48101518/77924995-0068d380-72ad-11ea-824f-4748bb0cc828.jpg)

**Comment by ZenkakuHiragana** [comment]
Thank you for reporting detailed explanation.
I'm working around lightmap of the ink (if it's incorrectly set up, the ink will look black or white)
Please wait for further updates or use an old version for now.

**Comment by ZenkakuHiragana** [comment]
I updated the sweps.
The lighting is still not that good, but somewhat better now.
Technically, GMOD doesn't have a way to get the lightmap and it's nearly impossible to draw correct lighting.
![gm_flounder_heights0000](https://user-images.githubusercontent.com/12111138/79192815-65532a80-7e64-11ea-8c50-e5b27cb005d2.jpg)
