### ISSUE TITLE
Brushes and rollers will always hit a prop, regardless of how small it is or if it's a prop gib.

### ISSUE THREAD

**Issue by bluedogz162** [ZenkakuHiragana/splatoonsweps#10]
https://user-images.githubusercontent.com/63551923/139619243-26aa3e63-5d97-4c4a-9fd9-52372d4719b0.mp4

**Comment by snowei19** [comment]
I'm pretty sure this behaviour has always been in the addon and an idea to fix this is to add a prop filter of some sorts, that makes the roller/brush ignore those small breakable props and gibs. Not sure how this would work with custom props though. 

I'm not a coder or anything so this idea could be impossible (T.T)

**Comment by ZenkakuHiragana** [comment]
Fixed.
