### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by TSYGANSokol** [ZenkakuHiragana/splatoonsweps#2]
Ink doesn't appear properly it just makes the area hit slightly darker.

sub weapons don't work

super jump doesn't work. (I assume it isn't implemented yet)

Wall swimming can get a bit buggy like getting stuck in walls if it has a lip (rare occurrence unable to recreate consistently). but the fact you are able to do it at all is impressive.

setting ink color values to 0 or 26 give nil value error and makes all ink sprayed and on the ground permanently invisible.

squids eyes don't work properly very minor issue.

enable and disable fall damage doesn't work (tested with and without realistic fall damage installed)

Besides those issues the mod is really great much better than it's predecessor if you have a kofi link or a patreon i would love to support you in that way. I love the aiming the arms do if there is a wall or floor in the way. overall the mod is amazing keep up the good work.

PC specs
graphics card:  GeForce GTX965M
Processor:  Intel Core i7-4720HQ CPU
OS: Windows 10 version 1903

**Comment by TSYGANSokol** [comment]
Also side question, Is there anyway to make water kill the player while the weapon is equipped or is all that handled by maps?

**Comment by snowei19** [comment]
Currently Zenkaku is working on a lightmap fix, which should fix the ink.
Sub weapons aren't yet implemented.
Here's his patreon. https://www.patreon.com/ZenkakuHiragana

**Comment by ZenkakuHiragana** [comment]
Thank you for posting a lot of issue with detailed explanation.
The answer of your side question is yes, I can make that "drowning" feature and I'm going to add it.

> setting ink color values to 0 or 26
That's simply because I don't implement colors for that numbers.

Also, I'm really glad to be donated.  I'll keep working on my work!

**Comment by ZenkakuHiragana** [comment]
> Ink doesn't appear properly it just makes the area hit slightly darker.
I updated the repository and it looks slightly better now.

> enable and disable fall damage doesn't work (tested with and without realistic fall damage installed)
I can't reproduce this issue.  Note that this setting only affects when you equip the Splatoon weapons.

**Comment by TSYGANSokol** [comment]
> I can't reproduce this issue. Note that this setting only affects when you equip the Splatoon weapons.

I am aware but i always take 10 fall damage no matter if its the settings are turned on or off. I will look into it. Might be a conflicting mod.

**Comment by ZenkakuHiragana** [comment]
> Also side question, Is there anyway to make water kill the player while the weapon is equipped or is all that handled by maps?

Now players can drown when they equip Splatoon weapons.  You can disable drowning in the server settings.

**Comment by TSYGANSokol** [comment]
So new I found a new bug involving the rollers and brushes.

There isn't a lua to go with it but, it won't lay ink down or at least the texture for ink. you are still able to swim within the area you painted but it doesn't show up. Only the initial attacks from the rollers and brushes show up.

**Comment by ZenkakuHiragana** [comment]
If the ink resolution setting is too low, it sometimes doesn't show up.

**Comment by TSYGANSokol** [comment]
So I finally discovered the mod conflict that lead to me always taking fall damage. It was a weapon addon known as the god fist which after looking at the code for it, has absolutely no reason in causing this bug, but what can you do lol.

**Comment by TSYGANSokol** [comment]
Also I did have a question about the implementation of the super jump and how it will be used/work?

**Comment by TSYGANSokol** [comment]
![image](https://user-images.githubusercontent.com/58644780/80762438-8e351a00-8b0a-11ea-896f-e65dae0c9a2f.png)
Certain Weapons end up looking black or the metal is overly reflective never a good middle ground.

**Comment by TSYGANSokol** [comment]
![image](https://user-images.githubusercontent.com/58644780/80762550-bf154f00-8b0a-11ea-9db0-93cd9dafa358.png)
Also the bamboozler end cover is dangling. I don't know if this was intentional or not.

**Comment by TSYGANSokol** [comment]
Lastly the Aerospray RG and LG both appear black with the latter having a greenish gold tint to it.

**Comment by TSYGANSokol** [comment]
![image](https://user-images.githubusercontent.com/58644780/80768418-5cc34b00-8b18-11ea-864d-fc337724e159.png)
decided to check hitboxes, i noticed the squid form gets hitboxes of its own, are you planning on removing the players hitboxes while in squid form or are you keeping both?

**Comment by ZenkakuHiragana** [comment]
> So I finally discovered the mod conflict that lead to me always taking fall damage. It was a weapon addon known as the god fist which after looking at the code for it, has absolutely no reason in causing this bug, but what can you do lol.

Could you show me the workshop link to that addon?

**Comment by TSYGANSokol** [comment]
So here is the link to the conflicting addon.
https://steamcommunity.com/sharedfiles/filedetails/?id=171093607

Also i appreciate how responsive you are to my questions and how quick you are at working on this mod. It's always a highlight to see this mod get updated, keep up the good work.

Last question I swear. Is there anyway to change the hitboxes when crouching to better resemble the squid instead of just an invisible crouching playermodel. If not that's fine but if there was a way to implement this, would you?

**Comment by ZenkakuHiragana** [comment]
> So here is the link to the conflicting addon.
> https://steamcommunity.com/sharedfiles/filedetails/?id=171093607

I looked into its code and found the reason is that this addon badly handles around fall damage; the hook should return nothing instead of the default value.  Therefore, I can't do anything about that.  
Here's its hook:
``` Lua
local function GH_GetFallDamage(ply, sp)
	wep = ply:GetActiveWeapon()
	
	if IsValid(wep) and wep.IsGodHand then
		if wep:GetDTBool(0) then
			return 0
		end
		
		if ply.Bombing != 0 then
			ply.Bombing = 0
			return 0
		end
	end
	
	if GetConVarNumber("mp_falldamage") > 0 then
		sp = sp - 580
		return sp * (100/(1024-580))
	end
	
	return 10
end

hook.Add("GetFallDamage", "GH_GetFallDamage", GH_GetFallDamage)
```

> Also i appreciate how responsive you are to my questions and how quick you are at working on this mod. It's always a highlight to see this mod get updated, keep up the good work.

Thank you, I will keep up my work.

> Last question I swear. Is there anyway to change the hitboxes when crouching to better resemble the squid instead of just an invisible crouching playermodel. If not that's fine but if there was a way to implement this, would you?

I guess there is no way to change hitboxes for crouching, but I think it's ok as the squids in the original game also has somewhat larger hitboxes than their appearance.

**Comment by TSYGANSokol** [comment]
![image](https://user-images.githubusercontent.com/58644780/81489615-acef8b00-9245-11ea-9fa6-d45104adf2d2.png)
So fun weird glitch i found on a specific map.
Delfino Plaza

**Comment by TSYGANSokol** [comment]
![image](https://user-images.githubusercontent.com/58644780/81489630-ef18cc80-9245-11ea-832d-c119834a40c2.png)
Even Weirder it cuts off after a certain point

**Comment by ZenkakuHiragana** [comment]
> So fun weird glitch i found on a specific map.

I confirmed that glitch on [this map](https://steamcommunity.com/sharedfiles/filedetails/?id=259832764) and found that the reason is the walls are actually translucent.

A similar issue happens on [gm_blackmesa_sigma](https://steamcommunity.com/sharedfiles/filedetails/?id=104483047) when you paint glass.  
This screenshot shows that you can't properly see translucent things through ink.  
![20200511110446_1](https://user-images.githubusercontent.com/12111138/81518016-abbe7b00-9377-11ea-9430-796b0c9b550e.jpg)

I can't fix this issue because it needs to correct the rendering order.

**Comment by ZenkakuHiragana** [comment]
> Wall swimming can get a bit buggy like getting stuck in walls if it has a lip (rare occurrence unable to recreate consistently). but the fact you are able to do it at all is impressive.
Finally the wall swimming issue is fixed.  You can now swim walls even if it has a small lip.
