### ISSUE TITLE
Targeting Reticle On Seeker Disappears After Switching to another Splatoon Weapon

### ISSUE THREAD

**Issue by RC-3197** [ZenkakuHiragana/splatoonsweps#20]
The seeker's targeting reticle disappears after changing to another splatoon weapon. The seeker itself still locks on, the reticle just doesn't appear.

Steps to reproduce:
1. Equip Carbon Roller Deco (Right click while targeting an NPC to verify it is working)
2. Equip any other splatoon weapon
3. Switch back to the carbon roller deco, and right click and target an NPC, and you'll see the targeting reticle is gone
4. Unequip the carbon roller deco, and re equip it to get the targeting reticle back.

Anyways, this is a really small bug, but I thought you might want to know about it.

**Comment by ZenkakuHiragana** [comment]
Sorry for late reply, but sadly I couldn't reproduce it on a single player game.  
Is it still happening? If not, it seems some updates silently fixed it.

**Comment by RC-3197** [comment]
Hi! The bug is still present for me, and since my instructions may be confusing, I now have recorded a video of the bug occurring, and the steps to reproduce:
This was done on gm_flatgrass with minimal mods installed (the issue still occurs with no other mods installed at all):
[Video of Bug](https://www.youtube.com/watch?v=M6olyimjOXA)

Like I said earlier, this seems to be a very minor bug, since un-equipping the weapon and then re-equipping the weapon restores the reticle.

**Comment by ZenkakuHiragana** [comment]
Fixed!

Thank you very much for investigation.  It really helped me figure out the issue.  
Actually it was happening because of my legacy code when I was using SWEP construction kit to draw weapons.

I could reproduce it and got rid of those code, then it no longer happens on my end.
