### ISSUE TITLE
Unable to paint terrain + lua errors while in squid form swimming in ink

### ISSUE THREAD

**Issue by SuperLeo25** [ZenkakuHiragana/splatoonsweps#21]
I've been trying multiple maps with this addon, but it looks like i'm unable to paint the terrain with any weapon (ink spreads, but doesn't color anything), while some of them won't even shoot (Roller, Paintbrush, etc.). It looks like i'm only able to paint only using secondary weapons (which work flawlessly).

OS: Windows 10
Gmod branch: x86_64
Mod build: code downloaded and mounted as for 07/20/2022

Nothing also seems to make conflict with the addon itself, so i'm not exactly sure what's causing that...

Also this is the LUA error that's showing up in the terminal and issues section, it seems like it will happen only while in squid form swimming in ink:

**[splatoonsweps-master] addons/splatoonsweps-master/lua/splatoonsweps/movement.lua:369: bad argument #2 to '__add' (Vector expected, got userdata)
    1. __add - [C]:-1
        2. CheckParameters - addons/splatoonsweps-master/lua/splatoonsweps/movement.lua:369
            3. SquidMove - addons/splatoonsweps-master/lua/splatoonsweps/movement.lua:1509
                4. v - addons/splatoonsweps-master/lua/splatoonsweps/movement.lua:1617
                    5. unknown - lua/includes/modules/hook.lua:96**

If screenshots and/or other stuff to track the issue will be needed, i'll provide them.

**Comment by ZenkakuHiragana** [comment]
Thank you for detailed explanation but I couldn't reproduce it on my quick test.

I would like to ask two more questions:

1. Is it single player?
2. Is there any error on map load?  
    Strange errors often happen if initialization failed for some reason.

And anything you found is appreciated.

**Comment by ZenkakuHiragana** [comment]
Alright, so, umm, what happens if you disable all the subscribed addons other than the required ones for the SWEPs?  
It seems quite strange, but I think one of your addons causes a conflict.

**Comment by ZenkakuHiragana** [comment]
Does this still happen?  I have updated the addon some times and I think it's time to see if it's fixed.
(I'm saying like that because I couldn't reproduce the issue at all.)

If it still exists, try disabling unrelated addons and report here again.

**Comment by SuperLeo25** [comment]
After a bit of time, i managed to try using again the addon only with the required dependencies. It worked well enough, and errors didn't show up like last time, but it was showing this error on each weapon i would pick up:

![Error that was shown when a weapon was given to player](https://user-images.githubusercontent.com/78843541/194595557-a53c75ff-bffc-4dab-b690-fcbb78c97809.png)

I'll do a better research on what was causing the conflict with other addons, then i'll report it here again.
