### ISSUE TITLE
Ink Error and Question.

### ISSUE THREAD

**Issue by JMiner07** [ZenkakuHiragana/splatoonsweps#3]
I keep getting errors when i shoot out ink. the ink goes half way then an error pops up, saying the lua file has a problem. oh! and question, does the Ink color change the color of ink on the weapon or no, it dosen't.

**Comment by ZenkakuHiragana** [comment]
1. Read the important things on the README as your post doesn't help me fix your issue.
2. Yes, the ink color does change it if you have Team Fortress 2 and mount it on Garry's Mod.

**Comment by JMiner07** [comment]
> 1. Read the important things on the README as your post doesn't help me fix your issue.
> 2. Yes, the ink color does change it if you have Team Fortress 2 and mount it on Garry's Mod.

1. i fixed the ink issue
2. does Team Fortress 2 need to be installed to mount it on Garry's Mod or no

**Comment by ZenkakuHiragana** [comment]
1. Then why did you post it here?
2. Yes
