### ISSUE TITLE
Sub weapon

### ISSUE THREAD

**Issue by TSYGANSokol** [ZenkakuHiragana/splatoonsweps#4]
Giving >TSY a weapon_splatoonsweps_splattershot_wasabi

[splatoonsweps-master] addons/splatoonsweps-master/lua/effects/splatoonswepslandingpoint.lua:44: bad argument #1 to 'SetPos' (Vector expected, got nil)
  1. SetPos - [C]:-1
   2. unknown - addons/splatoonsweps-master/lua/effects/splatoonswepslandingpoint.lua:44 (x6)

**Comment by ZenkakuHiragana** [comment]
Confirmed in singleplayer and fixed.
