### ISSUE TITLE
Unable to download an ink map on built-in Half-Life 2 maps

### ISSUE THREAD

**Issue by OctoRuslan** [ZenkakuHiragana/splatoonsweps#48]
### What happened
Upon loading into any HL2 map, I immediately receive the following errors:
[splatoonsweps-master] addons/splatoonsweps-master/lua/splatoonsweps/server/lightmap.lua:195: attempt to index field '_lighthdr' (a nil value)
  1. BuildLightmap - addons/splatoonsweps-master/lua/splatoonsweps/server/lightmap.lua:195
   2. v - addons/splatoonsweps-master/lua/splatoonsweps/server/autorun.lua:188
    3. unknown - lua/includes/modules/hook.lua:96
#### I have attempted the steps written in Known Issues, it didn't help.
Are HL2 maps just not supported or did I do something wrong?
### Steps to reproduce
1. Download and enable the addon
2. Load any built-in HL2 map
### My environment
OS: Win10
RAM: 32 GB, 24 GB allocated to GMod
VRAM: 36 GB
CPU: 11-th Gen Intel Core i5-11600KF
GPU: NVIDIA GeForce RTX 2060 SUPER
### Addons enabled (including splatoonsweps-master)
![addons](https://github.com/ZenkakuHiragana/splatoonsweps/assets/52858394/6e28934b-c549-412a-a4ae-f7f863567c61)

**Comment by ZenkakuHiragana** [comment]
Thank you for reporting and sorry for the inconvenience.
I think probably the recent updates broke the compatibility with non-HDR maps, just because of lack of tests.
I'll be busy for some weeks so I think I'll be able to investigate it next month.

**Comment by ZenkakuHiragana** [comment]
Finally I got enough time to work on this project again and I think it's fixed.
