### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by snowei19** [ZenkakuHiragana/splatoonsweps#5]
So I found these 2 bugs :

Bomb acting weirdly underwater
https://youtu.be/DhHEKp_ryog

Ink showing outside the skybox (idk)
![20200927201618_1](https://user-images.githubusercontent.com/48101518/94371545-06c2f580-0100-11eb-97de-213723181b58.jpg)

I'm pretty sure that there are no addons that cause these bugs
Also sorry if my english is bad

**Comment by ZenkakuHiragana** [comment]
Thank you for reporting.  I confirmed these issues.
I found the latter issue long ago, but I still can't find the way to fix it.

I'll keep trying to fix them.

**Comment by ZenkakuHiragana** [comment]
Probably fixed.
