### ISSUE TITLE
Squiffer has a slow charge mid-air

### ISSUE THREAD

**Issue by OctoRuslan** [ZenkakuHiragana/splatoonsweps#51]
This isn't a bug, rather just the lack of a weapon feature. Squiffer is meant to have a normal recharge while in mid-air, yet it doesn't in the mod. I'm not sure how it worked in the previous games, but at least it's the case for Splatoon 2 and 3.

**Comment by ZenkakuHiragana** [comment]
In fact, this is intended.  Squiffer in Splatoon 1 has a slow charge while jumping.
