### ISSUE TITLE
Level transitions break weapons

### ISSUE THREAD

**Issue by bluedogz162** [ZenkakuHiragana/splatoonsweps#6]
[https://drive.google.com/file/d/1nTYymNHWAa4hK4gJTed1dT4qwQdUzwva/view?usp=sharing](url)
Transitioning to another level via a changelevel trigger (used in most campaigns) breaks the weapons until you drop the weapons and re-create them from the spawnmenu.

**Comment by ZenkakuHiragana** [comment]
Confirmed in HL2 campaign maps and trying to fix it.  Thank you for reporting.

**Comment by ZenkakuHiragana** [comment]
Probably fixed.
